<a href="https://colab.research.google.com/github/vijjipammi/pub/blob/main/lstm_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers.core import Activation, Dropout, Dense
from keras.layers import Flatten, LSTM
from keras.layers import GlobalMaxPooling1D
from keras.models import Model
from keras.layers.embeddings import Embedding
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from keras.layers import Input
from keras.layers.merge import Concatenate
from keras.layers import Bidirectional

import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt

## Sequence Estimation for 1 Dimensional Input and One Dimensional Output

In [ ]:
X = list()
Y = list()
X = [x+1 for x in range(20)]
Y = [y * 15 for y in X]

print(X)
print(Y)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180, 195, 210, 225, 240, 255, 270, 285, 300]


In [ ]:
X = array(X).reshape(20, 1, 1)


In [ ]:
X.shape

(20, 1, 1)

In [ ]:
model = Sequential()
model.add(LSTM(10, activation='relu',return_sequences=True, input_shape=(1, 1)))
model.add(LSTM(10, activation='relu'))

model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 1, 10)             480       
_________________________________________________________________
lstm_2 (LSTM)                (None, 10)                840       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 1,331
Trainable params: 1,331
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.fit(X, Y, epochs=2000, validation_split=0.2, batch_size=5)


Train on 16 samples, validate on 4 samples
Epoch 1/2000
16/16 [==============================] - 1s 33ms/step - loss: 20960.8559 - val_loss: 76928.9219
Epoch 2/2000
16/16 [==============================] - 0s 731us/step - loss: 20947.8486 - val_loss: 76884.2188
Epoch 3/2000
16/16 [==============================] - 0s 499us/step - loss: 20935.4182 - val_loss: 76839.0156
Epoch 4/2000
16/16 [==============================] - 0s 416us/step - loss: 20921.4160 - val_loss: 76794.3594
Epoch 5/2000
16/16 [==============================] - 0s 605us/step - loss: 20907.6943 - val_loss: 76745.6875
Epoch 6/2000
16/16 [==============================] - 0s 499us/step - loss: 20894.2958 - val_loss: 76693.6797
Epoch 7/2000
16/16 [==============================] - 0s 499us/step - loss: 20879.4108 - val_loss: 76641.9219
Epoch 8/2000
16/16 [==============================] - 0s 436us/step - loss: 20864.1086 - val_loss: 76587.2969
Epoch 9/2000
16/16 [==============================] - 0s 253us/step - loss: 20

Epoch 75/2000
16/16 [==============================] - 0s 0us/step - loss: 7516.8210 - val_loss: 26325.6582
Epoch 76/2000
16/16 [==============================] - 0s 976us/step - loss: 7228.0608 - val_loss: 25258.4688
Epoch 77/2000
16/16 [==============================] - 0s 0us/step - loss: 6939.1683 - val_loss: 24207.3125
Epoch 78/2000
16/16 [==============================] - 0s 976us/step - loss: 6618.5619 - val_loss: 23227.6758
Epoch 79/2000
16/16 [==============================] - 0s 0us/step - loss: 6363.7257 - val_loss: 22227.3105
Epoch 80/2000
16/16 [==============================] - 0s 976us/step - loss: 6076.0963 - val_loss: 21290.4609
Epoch 81/2000
16/16 [==============================] - 0s 0us/step - loss: 5818.4876 - val_loss: 20346.3008
Epoch 82/2000
16/16 [==============================] - 0s 0us/step - loss: 5564.8497 - val_loss: 19462.2109
Epoch 83/2000
16/16 [==============================] - 0s 0us/step - loss: 5333.9210 - val_loss: 18596.1367
Epoch 84/2000
16/16 [=

16/16 [==============================] - 0s 976us/step - loss: 8.0819 - val_loss: 58.9527
Epoch 152/2000
16/16 [==============================] - 0s 0us/step - loss: 7.1255 - val_loss: 53.2593
Epoch 153/2000
16/16 [==============================] - 0s 976us/step - loss: 6.1011 - val_loss: 48.4455
Epoch 154/2000
16/16 [==============================] - 0s 0us/step - loss: 5.3421 - val_loss: 43.8979
Epoch 155/2000
16/16 [==============================] - 0s 976us/step - loss: 4.6827 - val_loss: 40.0460
Epoch 156/2000
16/16 [==============================] - 0s 0us/step - loss: 4.1235 - val_loss: 36.6828
Epoch 157/2000
16/16 [==============================] - 0s 977us/step - loss: 3.6242 - val_loss: 33.6898
Epoch 158/2000
16/16 [==============================] - 0s 0us/step - loss: 3.2668 - val_loss: 30.6516
Epoch 159/2000
16/16 [==============================] - 0s 976us/step - loss: 2.8339 - val_loss: 28.1609
Epoch 160/2000
16/16 [==============================] - 0s 0us/step - loss: 2.

Epoch 230/2000
16/16 [==============================] - 0s 976us/step - loss: 1.0498 - val_loss: 9.2134
Epoch 231/2000
16/16 [==============================] - 0s 0us/step - loss: 1.0470 - val_loss: 9.2775
Epoch 232/2000
16/16 [==============================] - 0s 976us/step - loss: 1.0438 - val_loss: 9.3944
Epoch 233/2000
16/16 [==============================] - 0s 0us/step - loss: 1.0404 - val_loss: 9.4846
Epoch 234/2000
16/16 [==============================] - 0s 976us/step - loss: 1.0381 - val_loss: 9.5459
Epoch 235/2000
16/16 [==============================] - 0s 0us/step - loss: 1.0334 - val_loss: 9.6191
Epoch 236/2000
16/16 [==============================] - 0s 976us/step - loss: 1.0316 - val_loss: 9.6993
Epoch 237/2000
16/16 [==============================] - 0s 0us/step - loss: 1.0276 - val_loss: 9.8216
Epoch 238/2000
16/16 [==============================] - 0s 976us/step - loss: 1.0242 - val_loss: 9.9547
Epoch 239/2000
16/16 [==============================] - 0s 0us/step - lo

16/16 [==============================] - 0s 976us/step - loss: 0.8651 - val_loss: 10.1723
Epoch 310/2000
16/16 [==============================] - 0s 0us/step - loss: 0.8619 - val_loss: 10.2624
Epoch 311/2000
16/16 [==============================] - 0s 0us/step - loss: 0.8597 - val_loss: 10.3463
Epoch 312/2000
16/16 [==============================] - 0s 976us/step - loss: 0.8577 - val_loss: 10.4625
Epoch 313/2000
16/16 [==============================] - 0s 0us/step - loss: 0.8562 - val_loss: 10.5721
Epoch 314/2000
16/16 [==============================] - 0s 976us/step - loss: 0.8540 - val_loss: 10.6183
Epoch 315/2000
16/16 [==============================] - 0s 0us/step - loss: 0.8517 - val_loss: 10.6175
Epoch 316/2000
16/16 [==============================] - 0s 976us/step - loss: 0.8490 - val_loss: 10.6736
Epoch 317/2000
16/16 [==============================] - 0s 0us/step - loss: 0.8466 - val_loss: 10.7373
Epoch 318/2000
16/16 [==============================] - 0s 976us/step - loss: 0.

16/16 [==============================] - 0s 0us/step - loss: 0.7130 - val_loss: 9.7213
Epoch 389/2000
16/16 [==============================] - 0s 976us/step - loss: 0.7110 - val_loss: 9.7478
Epoch 390/2000
16/16 [==============================] - 0s 0us/step - loss: 0.7095 - val_loss: 9.7926
Epoch 391/2000
16/16 [==============================] - 0s 976us/step - loss: 0.7076 - val_loss: 9.8142
Epoch 392/2000
16/16 [==============================] - 0s 0us/step - loss: 0.7064 - val_loss: 9.8012
Epoch 393/2000
16/16 [==============================] - 0s 976us/step - loss: 0.7034 - val_loss: 9.8714
Epoch 394/2000
16/16 [==============================] - 0s 0us/step - loss: 0.7011 - val_loss: 9.9399
Epoch 395/2000
16/16 [==============================] - 0s 0us/step - loss: 0.7007 - val_loss: 10.0674
Epoch 396/2000
16/16 [==============================] - 0s 976us/step - loss: 0.6996 - val_loss: 10.1059
Epoch 397/2000
16/16 [==============================] - 0s 0us/step - loss: 0.6978 - va

16/16 [==============================] - 0s 0us/step - loss: 0.5861 - val_loss: 9.5228
Epoch 468/2000
16/16 [==============================] - 0s 0us/step - loss: 0.5876 - val_loss: 9.6114
Epoch 469/2000
16/16 [==============================] - 0s 0us/step - loss: 0.5885 - val_loss: 9.4079
Epoch 470/2000
16/16 [==============================] - 0s 976us/step - loss: 0.5841 - val_loss: 9.3630
Epoch 471/2000
16/16 [==============================] - 0s 0us/step - loss: 0.5823 - val_loss: 9.3702
Epoch 472/2000
16/16 [==============================] - 0s 0us/step - loss: 0.5802 - val_loss: 9.4312
Epoch 473/2000
16/16 [==============================] - 0s 0us/step - loss: 0.5794 - val_loss: 9.4915
Epoch 474/2000
16/16 [==============================] - 0s 976us/step - loss: 0.5776 - val_loss: 9.5284
Epoch 475/2000
16/16 [==============================] - 0s 0us/step - loss: 0.5770 - val_loss: 9.6335
Epoch 476/2000
16/16 [==============================] - 0s 976us/step - loss: 0.5748 - val_lo

16/16 [==============================] - 0s 0us/step - loss: 0.4862 - val_loss: 9.5595
Epoch 547/2000
16/16 [==============================] - 0s 976us/step - loss: 0.4858 - val_loss: 9.6072
Epoch 548/2000
16/16 [==============================] - 0s 0us/step - loss: 0.4846 - val_loss: 9.6572
Epoch 549/2000
16/16 [==============================] - 0s 976us/step - loss: 0.4835 - val_loss: 9.6074
Epoch 550/2000
16/16 [==============================] - 0s 0us/step - loss: 0.4816 - val_loss: 9.5412
Epoch 551/2000
16/16 [==============================] - 0s 976us/step - loss: 0.4822 - val_loss: 9.4306
Epoch 552/2000
16/16 [==============================] - 0s 0us/step - loss: 0.4776 - val_loss: 9.3979
Epoch 553/2000
16/16 [==============================] - 0s 976us/step - loss: 0.4757 - val_loss: 9.1810
Epoch 554/2000
16/16 [==============================] - 0s 0us/step - loss: 0.4730 - val_loss: 8.9927
Epoch 555/2000
16/16 [==============================] - 0s 976us/step - loss: 0.4711 - va

Epoch 626/2000
16/16 [==============================] - 0s 0us/step - loss: 0.3879 - val_loss: 8.4715
Epoch 627/2000
16/16 [==============================] - 0s 977us/step - loss: 0.3867 - val_loss: 8.5210
Epoch 628/2000
16/16 [==============================] - 0s 0us/step - loss: 0.3884 - val_loss: 8.6876
Epoch 629/2000
16/16 [==============================] - 0s 976us/step - loss: 0.3847 - val_loss: 8.8050
Epoch 630/2000
16/16 [==============================] - 0s 0us/step - loss: 0.3859 - val_loss: 8.9391
Epoch 631/2000
16/16 [==============================] - 0s 976us/step - loss: 0.3849 - val_loss: 9.0257
Epoch 632/2000
16/16 [==============================] - 0s 0us/step - loss: 0.3852 - val_loss: 8.9897
Epoch 633/2000
16/16 [==============================] - 0s 976us/step - loss: 0.3831 - val_loss: 8.8399
Epoch 634/2000
16/16 [==============================] - 0s 0us/step - loss: 0.3779 - val_loss: 8.5117
Epoch 635/2000
16/16 [==============================] - 0s 976us/step - lo

16/16 [==============================] - 0s 0us/step - loss: 0.3125 - val_loss: 8.2648
Epoch 706/2000
16/16 [==============================] - 0s 0us/step - loss: 0.3135 - val_loss: 8.2188
Epoch 707/2000
16/16 [==============================] - 0s 0us/step - loss: 0.3105 - val_loss: 8.2930
Epoch 708/2000
16/16 [==============================] - 0s 0us/step - loss: 0.3102 - val_loss: 8.2837
Epoch 709/2000
16/16 [==============================] - 0s 976us/step - loss: 0.3090 - val_loss: 8.2275
Epoch 710/2000
16/16 [==============================] - 0s 0us/step - loss: 0.3093 - val_loss: 8.1850
Epoch 711/2000
16/16 [==============================] - 0s 976us/step - loss: 0.3050 - val_loss: 7.8808
Epoch 712/2000
16/16 [==============================] - 0s 0us/step - loss: 0.3010 - val_loss: 7.6071
Epoch 713/2000
16/16 [==============================] - 0s 976us/step - loss: 0.3091 - val_loss: 7.0773
Epoch 714/2000
16/16 [==============================] - 0s 0us/step - loss: 0.3066 - val_lo

Epoch 785/2000
16/16 [==============================] - 0s 0us/step - loss: 0.2400 - val_loss: 6.7721
Epoch 786/2000
16/16 [==============================] - 0s 0us/step - loss: 0.2396 - val_loss: 6.9569
Epoch 787/2000
16/16 [==============================] - 0s 976us/step - loss: 0.2372 - val_loss: 6.9786
Epoch 788/2000
16/16 [==============================] - 0s 0us/step - loss: 0.2364 - val_loss: 6.9634
Epoch 789/2000
16/16 [==============================] - 0s 976us/step - loss: 0.2360 - val_loss: 6.9885
Epoch 790/2000
16/16 [==============================] - 0s 976us/step - loss: 0.2349 - val_loss: 6.9452
Epoch 791/2000
16/16 [==============================] - 0s 0us/step - loss: 0.2338 - val_loss: 6.8890
Epoch 792/2000
16/16 [==============================] - 0s 976us/step - loss: 0.2328 - val_loss: 6.9077
Epoch 793/2000
16/16 [==============================] - 0s 0us/step - loss: 0.2330 - val_loss: 6.9982
Epoch 794/2000
16/16 [==============================] - 0s 976us/step - lo

16/16 [==============================] - 0s 976us/step - loss: 0.1817 - val_loss: 6.0972
Epoch 865/2000
16/16 [==============================] - 0s 0us/step - loss: 0.1798 - val_loss: 5.9877
Epoch 866/2000
16/16 [==============================] - 0s 977us/step - loss: 0.1788 - val_loss: 5.7963
Epoch 867/2000
16/16 [==============================] - 0s 0us/step - loss: 0.1783 - val_loss: 5.3722
Epoch 868/2000
16/16 [==============================] - 0s 976us/step - loss: 0.1816 - val_loss: 5.1708
Epoch 869/2000
16/16 [==============================] - 0s 0us/step - loss: 0.1881 - val_loss: 5.0935
Epoch 870/2000
16/16 [==============================] - 0s 0us/step - loss: 0.1849 - val_loss: 5.2851
Epoch 871/2000
16/16 [==============================] - 0s 976us/step - loss: 0.1795 - val_loss: 5.4699
Epoch 872/2000
16/16 [==============================] - 0s 0us/step - loss: 0.1784 - val_loss: 5.6828
Epoch 873/2000
16/16 [==============================] - 0s 976us/step - loss: 0.1752 - va

Epoch 944/2000
16/16 [==============================] - 0s 976us/step - loss: 0.1464 - val_loss: 4.2227
Epoch 945/2000
16/16 [==============================] - 0s 0us/step - loss: 0.1485 - val_loss: 4.2839
Epoch 946/2000
16/16 [==============================] - 0s 976us/step - loss: 0.1459 - val_loss: 4.3397
Epoch 947/2000
16/16 [==============================] - 0s 0us/step - loss: 0.1421 - val_loss: 4.4646
Epoch 948/2000
16/16 [==============================] - 0s 0us/step - loss: 0.1388 - val_loss: 4.6868
Epoch 949/2000
16/16 [==============================] - 0s 976us/step - loss: 0.1332 - val_loss: 4.8818
Epoch 950/2000
16/16 [==============================] - 0s 0us/step - loss: 0.1305 - val_loss: 5.1262
Epoch 951/2000
16/16 [==============================] - 0s 976us/step - loss: 0.1306 - val_loss: 5.2666
Epoch 952/2000
16/16 [==============================] - 0s 0us/step - loss: 0.1308 - val_loss: 5.3775
Epoch 953/2000
16/16 [==============================] - 0s 976us/step - lo

16/16 [==============================] - 0s 976us/step - loss: 0.0990 - val_loss: 4.2766
Epoch 1024/2000
16/16 [==============================] - 0s 0us/step - loss: 0.1009 - val_loss: 3.7352
Epoch 1025/2000
16/16 [==============================] - 0s 0us/step - loss: 0.1159 - val_loss: 3.5058
Epoch 1026/2000
16/16 [==============================] - 0s 976us/step - loss: 0.1211 - val_loss: 3.6122
Epoch 1027/2000
16/16 [==============================] - 0s 0us/step - loss: 0.1154 - val_loss: 3.7658
Epoch 1028/2000
16/16 [==============================] - 0s 976us/step - loss: 0.1107 - val_loss: 3.9058
Epoch 1029/2000
16/16 [==============================] - 0s 0us/step - loss: 0.1054 - val_loss: 4.0192
Epoch 1030/2000
16/16 [==============================] - 0s 976us/step - loss: 0.1022 - val_loss: 4.1808
Epoch 1031/2000
16/16 [==============================] - 0s 0us/step - loss: 0.1012 - val_loss: 4.3791
Epoch 1032/2000
16/16 [==============================] - 0s 0us/step - loss: 0.09

16/16 [==============================] - 0s 976us/step - loss: 0.0803 - val_loss: 3.9213
Epoch 1103/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0809 - val_loss: 3.6881
Epoch 1104/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0821 - val_loss: 3.5840
Epoch 1105/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0832 - val_loss: 3.6182
Epoch 1106/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0820 - val_loss: 3.6518
Epoch 1107/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0814 - val_loss: 3.7625
Epoch 1108/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0798 - val_loss: 3.9942
Epoch 1109/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0784 - val_loss: 4.1775
Epoch 1110/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0812 - val_loss: 4.3127
Epoch 1111/2000
16/16 [==============================] - 0s 976us/step - loss: 0.08

Epoch 1181/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0700 - val_loss: 3.9247
Epoch 1182/2000
16/16 [==============================] - 0s 1ms/step - loss: 0.0696 - val_loss: 3.8452
Epoch 1183/2000
16/16 [==============================] - 0s 373us/step - loss: 0.0686 - val_loss: 3.8042
Epoch 1184/2000
16/16 [==============================] - 0s 374us/step - loss: 0.0678 - val_loss: 3.8247
Epoch 1185/2000
16/16 [==============================] - 0s 379us/step - loss: 0.0682 - val_loss: 3.8054
Epoch 1186/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0675 - val_loss: 3.7046
Epoch 1187/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0662 - val_loss: 3.5934
Epoch 1188/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0658 - val_loss: 3.4734
Epoch 1189/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0661 - val_loss: 3.3671
Epoch 1190/2000
16/16 [==============================] - 0s 976us

16/16 [==============================] - 0s 976us/step - loss: 0.0601 - val_loss: 3.4997
Epoch 1260/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0604 - val_loss: 3.3465
Epoch 1261/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0592 - val_loss: 3.1971
Epoch 1262/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0578 - val_loss: 3.0969
Epoch 1263/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0576 - val_loss: 3.0715
Epoch 1264/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0586 - val_loss: 3.2369
Epoch 1265/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0575 - val_loss: 3.2780
Epoch 1266/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0572 - val_loss: 3.2929
Epoch 1267/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0576 - val_loss: 3.3598
Epoch 1268/2000
16/16 [==============================] - 0s 976us/step - loss: 0.

16/16 [==============================] - 0s 0us/step - loss: 0.0512 - val_loss: 2.8663
Epoch 1339/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0510 - val_loss: 2.8018
Epoch 1340/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0511 - val_loss: 2.7412
Epoch 1341/2000
16/16 [==============================] - ETA: 0s - loss: 0.018 - 0s 0us/step - loss: 0.0520 - val_loss: 2.6886
Epoch 1342/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0521 - val_loss: 2.4975
Epoch 1343/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0537 - val_loss: 2.6404
Epoch 1344/2000
16/16 [==============================] - 0s 975us/step - loss: 0.0510 - val_loss: 2.9398
Epoch 1345/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0516 - val_loss: 3.1626
Epoch 1346/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0549 - val_loss: 3.3184
Epoch 1347/2000
16/16 [==============================] - 0s 0

Epoch 1417/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0462 - val_loss: 2.7099
Epoch 1418/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0468 - val_loss: 2.7508
Epoch 1419/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0491 - val_loss: 2.9062
Epoch 1420/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0482 - val_loss: 2.8720
Epoch 1421/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0464 - val_loss: 2.6227
Epoch 1422/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0437 - val_loss: 2.1722
Epoch 1423/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0575 - val_loss: 1.9880
Epoch 1424/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0608 - val_loss: 2.0605
Epoch 1425/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0554 - val_loss: 2.2611
Epoch 1426/2000
16/16 [==============================] - 0s 976us/s

Epoch 1496/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0432 - val_loss: 2.5917
Epoch 1497/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0430 - val_loss: 2.5838
Epoch 1498/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0440 - val_loss: 2.6744
Epoch 1499/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0438 - val_loss: 2.5734
Epoch 1500/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0438 - val_loss: 2.4379
Epoch 1501/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0418 - val_loss: 2.5672
Epoch 1502/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0447 - val_loss: 2.7466
Epoch 1503/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0446 - val_loss: 2.6687
Epoch 1504/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0417 - val_loss: 2.4866
Epoch 1505/2000
16/16 [==============================] - 0s 976us

Epoch 1575/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0429 - val_loss: 2.9442
Epoch 1576/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0520 - val_loss: 2.8505
Epoch 1577/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0462 - val_loss: 2.5221
Epoch 1578/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0415 - val_loss: 2.2911
Epoch 1579/2000
16/16 [==============================] - 0s 293us/step - loss: 0.0390 - val_loss: 2.3438
Epoch 1580/2000
16/16 [==============================] - 0s 429us/step - loss: 0.0386 - val_loss: 2.3768
Epoch 1581/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0387 - val_loss: 2.3802
Epoch 1582/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0388 - val_loss: 2.4166
Epoch 1583/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0388 - val_loss: 2.3462
Epoch 1584/2000
16/16 [==============================] - 0s 976

Epoch 1654/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0441 - val_loss: 2.0771
Epoch 1655/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0353 - val_loss: 1.9372
Epoch 1656/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0362 - val_loss: 1.9584
Epoch 1657/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0365 - val_loss: 1.9625
Epoch 1658/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0356 - val_loss: 2.0569
Epoch 1659/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0354 - val_loss: 1.9437
Epoch 1660/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0430 - val_loss: 1.6738
Epoch 1661/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0409 - val_loss: 1.9761
Epoch 1662/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0351 - val_loss: 2.1445
Epoch 1663/2000
16/16 [==============================] - 0s 976us

Epoch 1733/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0337 - val_loss: 1.8117
Epoch 1734/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0330 - val_loss: 1.8803
Epoch 1735/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0323 - val_loss: 1.9288
Epoch 1736/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0322 - val_loss: 1.9393
Epoch 1737/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0318 - val_loss: 1.9138
Epoch 1738/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0335 - val_loss: 2.0182
Epoch 1739/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0317 - val_loss: 2.2017
Epoch 1740/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0368 - val_loss: 2.3468
Epoch 1741/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0367 - val_loss: 2.1317
Epoch 1742/2000
16/16 [==============================] - 0s 976us

Epoch 1812/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0343 - val_loss: 2.2615
Epoch 1813/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0365 - val_loss: 2.0797
Epoch 1814/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0313 - val_loss: 1.7630
Epoch 1815/2000
16/16 [==============================] - 0s 976us/step - loss: 0.0296 - val_loss: 1.7344
Epoch 1816/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0293 - val_loss: 1.7420
Epoch 1817/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0294 - val_loss: 1.7398
Epoch 1818/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0295 - val_loss: 1.7296
Epoch 1819/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0299 - val_loss: 1.7924
Epoch 1820/2000
16/16 [==============================] - 0s 0us/step - loss: 0.0281 - val_loss: 1.9884
Epoch 1821/2000
16/16 [==============================] - 0s 0us/step 

Epoch 1891/2000
16/16 [==============================] - 0s 499us/step - loss: 0.0305 - val_loss: 2.0408
Epoch 1892/2000
16/16 [==============================] - 0s 436us/step - loss: 0.0314 - val_loss: 1.7252
Epoch 1893/2000
16/16 [==============================] - 0s 436us/step - loss: 0.0263 - val_loss: 1.5207
Epoch 1894/2000
16/16 [==============================] - 0s 436us/step - loss: 0.0271 - val_loss: 1.7209
Epoch 1895/2000
16/16 [==============================] - 0s 436us/step - loss: 0.0290 - val_loss: 1.8695
Epoch 1896/2000
16/16 [==============================] - 0s 686us/step - loss: 0.0283 - val_loss: 1.7299
Epoch 1897/2000
16/16 [==============================] - 0s 561us/step - loss: 0.0272 - val_loss: 1.7959
Epoch 1898/2000
16/16 [==============================] - 0s 499us/step - loss: 0.0268 - val_loss: 1.9106
Epoch 1899/2000
16/16 [==============================] - 0s 499us/step - loss: 0.0284 - val_loss: 1.8858
Epoch 1900/2000
16/16 [==============================] 

16/16 [==============================] - 0s 436us/step - loss: 0.0240 - val_loss: 2.0649
Epoch 1970/2000
16/16 [==============================] - 0s 374us/step - loss: 0.0344 - val_loss: 2.1198
Epoch 1971/2000
16/16 [==============================] - 0s 499us/step - loss: 0.0323 - val_loss: 1.6232
Epoch 1972/2000
16/16 [==============================] - 0s 436us/step - loss: 0.0255 - val_loss: 1.6049
Epoch 1973/2000
16/16 [==============================] - 0s 436us/step - loss: 0.0264 - val_loss: 1.7543
Epoch 1974/2000
16/16 [==============================] - 0s 436us/step - loss: 0.0268 - val_loss: 1.5372
Epoch 1975/2000
16/16 [==============================] - 0s 499us/step - loss: 0.0258 - val_loss: 1.6020
Epoch 1976/2000
16/16 [==============================] - 0s 436us/step - loss: 0.0245 - val_loss: 1.6094
Epoch 1977/2000
16/16 [==============================] - 0s 436us/step - loss: 0.0244 - val_loss: 1.5688
Epoch 1978/2000
16/16 [==============================] - 0s 73us/step -

In [ ]:
test_input = array([8])
test_input = test_input.reshape((1, 1, 1))
test_output = model.predict(test_input, verbose=0)
print(test_output)

[[119.94444]]


## Sequence Estimation for 2 Dimensional Input and One Dimensional Output

In [ ]:
nums = 1000

X1 = list()
X2 = list()
X = list()
Y = list()
X1 = np.random.uniform(0,20,1000)
X2 = np.random.uniform(0,20,1000)

Y = [2*x1+x2 for x1,x2 in zip(X1,X2)]


print(X1)
print(X2)
print(Y)

[13.61404994  2.12815014  9.24732253 17.91914729 13.26118389 11.49314885
 16.72234031  1.46413553 17.39630046 16.93812883  3.99676761  0.75689572
 18.25427115 13.63264856  5.09913165  0.50306863  9.28400176 13.28322428
 15.43880086 11.16611436 19.74414053 18.65657158 12.52040837 12.55943378
  3.85082828 14.51637533 13.52169277 15.81952356  8.68059616 10.8111324
 18.99174379  4.02466257  8.91020745  0.24242416  4.08500018  5.75809102
  3.28929346 12.8474433  17.2158367   1.37356573  1.97819735  4.99683447
  7.62434365  5.55535834 13.61296424  7.27322231  7.812845   19.00727621
  3.19937102  9.39071788 19.1756287   8.50550845 18.89848427 19.87583603
  1.68961912 13.58819552 10.52566415 19.21899621  7.0140757   7.16732439
 14.58721817  4.49875237 13.66610343  8.0406147  15.60718035 18.58234117
 10.86120395 18.50410043  8.34555847  5.97971113 17.59931923 18.54629951
 17.37660421  0.66070822 13.02188785  1.94368899 17.40364809 18.61628073
  6.22123413  5.61405047  9.70092833 13.14089891 15.

In [ ]:
X1= np.array(X1).reshape(-1,1)

In [ ]:
X2=np.array(X2).reshape(-1,1)

In [ ]:
X1.shape

(1000, 1)

In [ ]:
X=np.concatenate((X1, X2), axis=1)

In [ ]:
#X = np.column_stack((X1, X2))
print(X)

[[13.61404994  0.17317094]
 [ 2.12815014  3.40479077]
 [ 9.24732253 13.98276647]
 ...
 [15.94832169 19.82674835]
 [13.5844915   3.52955663]
 [12.34366353 16.25051553]]


In [ ]:
X = array(X).reshape(1000, 1, 2)


In [ ]:
X.shape

(1000, 1, 2)

In [ ]:
model = Sequential()
model.add(LSTM(20, activation='relu', input_shape=(1, 2)))



model.add(Dense(10, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 20)                1840      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                210       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 11        
Total params: 2,061
Trainable params: 2,061
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
X.shape

(1000, 1, 2)

In [ ]:
Y.shape

AttributeError: 'list' object has no attribute 'shape'

In [ ]:
model.compile(optimizer='adam', loss='mse')


In [ ]:
model.fit(X, Y, epochs=500, validation_split=0.2, shuffle=True, batch_size=5)


Train on 800 samples, validate on 200 samples
Epoch 1/500
800/800 [==============================] - 0s 559us/step - loss: 875.7121 - val_loss: 243.9020
Epoch 2/500
800/800 [==============================] - 0s 234us/step - loss: 25.1967 - val_loss: 3.4513
Epoch 3/500
800/800 [==============================] - 0s 197us/step - loss: 1.7343 - val_loss: 0.9421
Epoch 4/500
800/800 [==============================] - 0s 196us/step - loss: 0.6229 - val_loss: 0.4759
Epoch 5/500
800/800 [==============================] - 0s 217us/step - loss: 0.3165 - val_loss: 0.2364
Epoch 6/500
800/800 [==============================] - 0s 199us/step - loss: 0.1699 - val_loss: 0.1214
Epoch 7/500
800/800 [==============================] - 0s 189us/step - loss: 0.0992 - val_loss: 0.0747
Epoch 8/500
800/800 [==============================] - 0s 197us/step - loss: 0.0653 - val_loss: 0.0537
Epoch 9/500
800/800 [==============================] - 0s 208us/step - loss: 0.0492 - val_loss: 0.0432
Epoch 10/500
800/800 [

800/800 [==============================] - 0s 228us/step - loss: 0.0024 - val_loss: 7.2569e-04
Epoch 153/500
800/800 [==============================] - 0s 214us/step - loss: 8.9968e-04 - val_loss: 1.8171e-04
Epoch 154/500
800/800 [==============================] - 0s 227us/step - loss: 5.1113e-04 - val_loss: 0.0011
Epoch 155/500
800/800 [==============================] - 0s 221us/step - loss: 2.8090e-04 - val_loss: 2.5547e-04
Epoch 156/500
800/800 [==============================] - 0s 221us/step - loss: 2.5611e-04 - val_loss: 2.2474e-04
Epoch 157/500
800/800 [==============================] - 0s 217us/step - loss: 3.9637e-04 - val_loss: 4.3266e-04
Epoch 158/500
800/800 [==============================] - 0s 222us/step - loss: 0.0069 - val_loss: 4.8008e-04
Epoch 159/500
800/800 [==============================] - 0s 228us/step - loss: 1.4721e-04 - val_loss: 4.6268e-05
Epoch 160/500
800/800 [==============================] - 0s 229us/step - loss: 3.7780e-04 - val_loss: 6.4412e-05
Epoch 161

800/800 [==============================] - 0s 225us/step - loss: 6.7438e-04 - val_loss: 4.8778e-04
Epoch 299/500
800/800 [==============================] - 0s 223us/step - loss: 3.5151e-04 - val_loss: 5.7211e-05
Epoch 300/500
800/800 [==============================] - 0s 209us/step - loss: 1.0838e-04 - val_loss: 1.6140e-04
Epoch 301/500
800/800 [==============================] - 0s 231us/step - loss: 4.8848e-04 - val_loss: 0.0027
Epoch 302/500
800/800 [==============================] - 0s 221us/step - loss: 6.3243e-04 - val_loss: 8.1385e-05
Epoch 303/500
800/800 [==============================] - 0s 222us/step - loss: 4.0586e-04 - val_loss: 3.2316e-04
Epoch 304/500
800/800 [==============================] - 0s 218us/step - loss: 2.2773e-04 - val_loss: 0.0012
Epoch 305/500
800/800 [==============================] - 0s 238us/step - loss: 3.9666e-04 - val_loss: 1.8998e-04
Epoch 306/500
800/800 [==============================] - 0s 231us/step - loss: 0.0054 - val_loss: 3.3357e-04
Epoch 307

800/800 [==============================] - 0s 225us/step - loss: 2.8711e-04 - val_loss: 0.0019
Epoch 445/500
800/800 [==============================] - 0s 220us/step - loss: 3.0955e-04 - val_loss: 1.9412e-05
Epoch 446/500
800/800 [==============================] - 0s 228us/step - loss: 6.0918e-05 - val_loss: 2.8945e-04
Epoch 447/500
800/800 [==============================] - 0s 244us/step - loss: 0.0032 - val_loss: 1.6849e-04
Epoch 448/500
800/800 [==============================] - 0s 236us/step - loss: 4.1696e-04 - val_loss: 2.9544e-04
Epoch 449/500
800/800 [==============================] - 0s 218us/step - loss: 5.9038e-05 - val_loss: 6.9821e-05
Epoch 450/500
800/800 [==============================] - 0s 242us/step - loss: 0.0010 - val_loss: 8.6912e-04
Epoch 451/500
800/800 [==============================] - 0s 223us/step - loss: 3.5977e-04 - val_loss: 4.7556e-05
Epoch 452/500
800/800 [==============================] - 0s 223us/step - loss: 1.2496e-04 - val_loss: 1.9231e-05
Epoch 453

In [ ]:
x_test=np.ones((1,1,2))

In [ ]:
x_test

array([[[1., 1.]]])

In [ ]:
X_test=np.array([[1,]])

In [ ]:
model.predict(np.array([[[10.,10.]]]))

array([[29.98069]], dtype=float32)

In [ ]:
for i in range(1000):
    

## Many to One LSTM Problems

In [ ]:
X = np.array([x+1 for x in range(45)])
print(X)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45]


In [ ]:
X = X.reshape(15,3,1)
print(X)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]

 [[13]
  [14]
  [15]]

 [[16]
  [17]
  [18]]

 [[19]
  [20]
  [21]]

 [[22]
  [23]
  [24]]

 [[25]
  [26]
  [27]]

 [[28]
  [29]
  [30]]

 [[31]
  [32]
  [33]]

 [[34]
  [35]
  [36]]

 [[37]
  [38]
  [39]]

 [[40]
  [41]
  [42]]

 [[43]
  [44]
  [45]]]


In [ ]:
Y = list()
for x in X:
    Y.append(x.sum())

Y = np.array(Y)
print(Y)

[  6  15  24  33  42  51  60  69  78  87  96 105 114 123 132]


In [ ]:
model = Sequential()
model.add(LSTM(20, activation='relu', input_shape=(3, 1)))



model.add(Dense(10, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
print(model.summary())

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_15 (LSTM)               (None, 20)                1760      
_________________________________________________________________
dense_17 (Dense)             (None, 10)                210       
_________________________________________________________________
dense_18 (Dense)             (None, 1)                 11        
Total params: 1,981
Trainable params: 1,981
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.fit(X, Y, epochs=500, validation_split=0.2, shuffle=True, batch_size=5)


Train on 12 samples, validate on 3 samples
Epoch 1/500
12/12 [==============================] - 0s 24ms/step - loss: 4584.1268 - val_loss: 17253.9980
Epoch 2/500
12/12 [==============================] - 0s 582us/step - loss: 4546.2396 - val_loss: 17128.7969
Epoch 3/500
12/12 [==============================] - 0s 665us/step - loss: 4510.1804 - val_loss: 16996.3945
Epoch 4/500
12/12 [==============================] - 0s 748us/step - loss: 4477.9711 - val_loss: 16861.6699
Epoch 5/500
12/12 [==============================] - 0s 914us/step - loss: 4437.3061 - val_loss: 16731.6973
Epoch 6/500
12/12 [==============================] - 0s 831us/step - loss: 4397.9625 - val_loss: 16597.9531
Epoch 7/500
12/12 [==============================] - 0s 914us/step - loss: 4358.7086 - val_loss: 16457.8398
Epoch 8/500
12/12 [==============================] - 0s 831us/step - loss: 4315.6039 - val_loss: 16298.6484
Epoch 9/500
12/12 [==============================] - 0s 748us/step - loss: 4266.9693 - val_los

Epoch 78/500
12/12 [==============================] - 0s 582us/step - loss: 6.0188 - val_loss: 2.5229
Epoch 79/500
12/12 [==============================] - 0s 582us/step - loss: 5.9561 - val_loss: 2.8692
Epoch 80/500
12/12 [==============================] - 0s 831us/step - loss: 5.8973 - val_loss: 3.0396
Epoch 81/500
12/12 [==============================] - 0s 665us/step - loss: 5.7934 - val_loss: 2.7226
Epoch 82/500
12/12 [==============================] - 0s 665us/step - loss: 5.7207 - val_loss: 2.5708
Epoch 83/500
12/12 [==============================] - 0s 582us/step - loss: 5.6294 - val_loss: 2.3395
Epoch 84/500
12/12 [==============================] - 0s 582us/step - loss: 5.5540 - val_loss: 2.1906
Epoch 85/500
12/12 [==============================] - 0s 582us/step - loss: 5.4725 - val_loss: 1.9308
Epoch 86/500
12/12 [==============================] - 0s 499us/step - loss: 5.4205 - val_loss: 1.5850
Epoch 87/500
12/12 [==============================] - 0s 582us/step - loss: 5.3383

Epoch 158/500
12/12 [==============================] - 0s 582us/step - loss: 1.4950 - val_loss: 0.5438
Epoch 159/500
12/12 [==============================] - 0s 582us/step - loss: 1.4543 - val_loss: 0.5018
Epoch 160/500
12/12 [==============================] - 0s 665us/step - loss: 1.4423 - val_loss: 0.4205
Epoch 161/500
12/12 [==============================] - 0s 582us/step - loss: 1.4124 - val_loss: 0.4099
Epoch 162/500
12/12 [==============================] - 0s 582us/step - loss: 1.3933 - val_loss: 0.4007
Epoch 163/500
12/12 [==============================] - 0s 748us/step - loss: 1.3753 - val_loss: 0.4107
Epoch 164/500
12/12 [==============================] - 0s 665us/step - loss: 1.3570 - val_loss: 0.4656
Epoch 165/500
12/12 [==============================] - 0s 582us/step - loss: 1.3356 - val_loss: 0.6221
Epoch 166/500
12/12 [==============================] - 0s 665us/step - loss: 1.3012 - val_loss: 0.7040
Epoch 167/500
12/12 [==============================] - 0s 665us/step - lo

12/12 [==============================] - 0s 499us/step - loss: 0.0977 - val_loss: 0.0063
Epoch 317/500
12/12 [==============================] - 0s 499us/step - loss: 0.0963 - val_loss: 0.0029
Epoch 318/500
12/12 [==============================] - 0s 582us/step - loss: 0.0942 - val_loss: 0.0358
Epoch 319/500
12/12 [==============================] - 0s 581us/step - loss: 0.0964 - val_loss: 8.5841e-04
Epoch 320/500
12/12 [==============================] - 0s 499us/step - loss: 0.0949 - val_loss: 0.0119
Epoch 321/500
12/12 [==============================] - 0s 582us/step - loss: 0.0938 - val_loss: 0.0258
Epoch 322/500
12/12 [==============================] - 0s 582us/step - loss: 0.0897 - val_loss: 9.1649e-04
Epoch 323/500
12/12 [==============================] - 0s 582us/step - loss: 0.0885 - val_loss: 0.0199
Epoch 324/500
12/12 [==============================] - 0s 582us/step - loss: 0.0871 - val_loss: 0.0112
Epoch 325/500
12/12 [==============================] - 0s 582us/step - loss: 0.

Epoch 473/500
12/12 [==============================] - 0s 665us/step - loss: 0.0134 - val_loss: 3.1193e-04
Epoch 474/500
12/12 [==============================] - 0s 665us/step - loss: 0.0129 - val_loss: 0.0029
Epoch 475/500
12/12 [==============================] - 0s 746us/step - loss: 0.0129 - val_loss: 0.0018
Epoch 476/500
12/12 [==============================] - 0s 748us/step - loss: 0.0129 - val_loss: 6.2249e-05
Epoch 477/500
12/12 [==============================] - 0s 750us/step - loss: 0.0131 - val_loss: 0.0010
Epoch 478/500
12/12 [==============================] - 0s 665us/step - loss: 0.0125 - val_loss: 0.0030
Epoch 479/500
12/12 [==============================] - 0s 665us/step - loss: 0.0124 - val_loss: 0.0028
Epoch 480/500
12/12 [==============================] - 0s 665us/step - loss: 0.0121 - val_loss: 2.3934e-04
Epoch 481/500
12/12 [==============================] - 0s 664us/step - loss: 0.0123 - val_loss: 6.3279e-04
Epoch 482/500
12/12 [==============================] - 0s

In [ ]:
model.predict(np.array([[[4.],[5.],[6.]]]))

array([[15.151405]], dtype=float32)

In [ ]:
X=np.random.uniform(20,size=(1000,10))

In [ ]:
X.shape

(1000, 10)

In [ ]:
y=[]

In [ ]:
for x in X:
    y.append(x[0]+x[1]+5*x[2]+9*x[9])

In [ ]:
y=np.array(y)

In [ ]:
y.shape

(1000,)

In [ ]:
X.shape

(1000, 10)

In [ ]:
X=X.reshape(1000,10,1)

In [ ]:
model = Sequential()
model.add(LSTM(20, activation='relu', input_shape=(10, 1), return_sequences=True))
model.add(LSTM(20, activation='relu'))



model.add(Dense(10, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
print(model.summary())

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_20 (LSTM)               (None, 10, 20)            1760      
_________________________________________________________________
lstm_21 (LSTM)               (None, 20)                3280      
_________________________________________________________________
dense_21 (Dense)             (None, 10)                210       
_________________________________________________________________
dense_22 (Dense)             (None, 1)                 11        
Total params: 5,261
Trainable params: 5,261
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.compile(optimizer='adam', loss='mse')


In [ ]:
model.fit(X, y, epochs=500, validation_split=0.2, shuffle=True, batch_size=5)


Train on 800 samples, validate on 200 samples
Epoch 1/500
800/800 [==============================] - 1s 2ms/step - loss: 10815.1740 - val_loss: 2976.6415
Epoch 2/500
800/800 [==============================] - 1s 942us/step - loss: 2102.7354 - val_loss: 1175.4745
Epoch 3/500
800/800 [==============================] - 1s 941us/step - loss: 1258.2618 - val_loss: 1161.1582
Epoch 4/500
800/800 [==============================] - 1s 945us/step - loss: 1358.5360 - val_loss: 1023.6908
Epoch 5/500
800/800 [==============================] - 1s 933us/step - loss: 1101.9426 - val_loss: 962.2832
Epoch 6/500
800/800 [==============================] - 1s 945us/step - loss: 1041.4829 - val_loss: 858.5984
Epoch 7/500
800/800 [==============================] - 1s 946us/step - loss: 898.1065 - val_loss: 990.1506
Epoch 8/500
800/800 [==============================] - 1s 941us/step - loss: 789.0600 - val_loss: 746.6462
Epoch 9/500
800/800 [==============================] - 1s 952us/step - loss: 766.7912 - v

800/800 [==============================] - 1s 1ms/step - loss: 6.0239 - val_loss: 4.4130
Epoch 79/500
800/800 [==============================] - 1s 1ms/step - loss: 6.0421 - val_loss: 4.6251
Epoch 80/500
800/800 [==============================] - 1s 1ms/step - loss: 4.7090 - val_loss: 3.6584
Epoch 81/500
800/800 [==============================] - 1s 1ms/step - loss: 8.3047 - val_loss: 13.6556
Epoch 82/500
800/800 [==============================] - 1s 1ms/step - loss: 7.8479 - val_loss: 3.4388
Epoch 83/500
800/800 [==============================] - 1s 1ms/step - loss: 7.0497 - val_loss: 4.4287
Epoch 84/500
800/800 [==============================] - 1s 1ms/step - loss: 4.4363 - val_loss: 5.4378
Epoch 85/500
800/800 [==============================] - 1s 1ms/step - loss: 3.9295 - val_loss: 2.0826
Epoch 86/500
800/800 [==============================] - 1s 1ms/step - loss: 8.5044 - val_loss: 8.1455
Epoch 87/500
800/800 [==============================] - 1s 1ms/step - loss: 6.3112 - val_loss:

Epoch 158/500
800/800 [==============================] - 1s 1ms/step - loss: 4.6849 - val_loss: 1.4039
Epoch 159/500
800/800 [==============================] - 1s 1ms/step - loss: 2.1045 - val_loss: 0.8218
Epoch 160/500
800/800 [==============================] - 1s 1ms/step - loss: 0.9475 - val_loss: 3.9438
Epoch 161/500
800/800 [==============================] - 1s 1ms/step - loss: 0.9056 - val_loss: 0.5392
Epoch 162/500
800/800 [==============================] - 1s 1ms/step - loss: 2.8351 - val_loss: 9.0363
Epoch 163/500
800/800 [==============================] - 1s 1ms/step - loss: 1.7469 - val_loss: 1.3612
Epoch 164/500
800/800 [==============================] - 1s 1ms/step - loss: 1.8076 - val_loss: 0.9393
Epoch 165/500
800/800 [==============================] - 1s 1ms/step - loss: 0.8163 - val_loss: 1.2464
Epoch 166/500
800/800 [==============================] - 1s 1ms/step - loss: 4.0389 - val_loss: 4.1131
Epoch 167/500
800/800 [==============================] - 1s 1ms/step - lo

800/800 [==============================] - 1s 1ms/step - loss: 0.7459 - val_loss: 0.4569
Epoch 317/500
800/800 [==============================] - 1s 1ms/step - loss: 1.6134 - val_loss: 0.5566
Epoch 318/500
800/800 [==============================] - 1s 1ms/step - loss: 0.6864 - val_loss: 1.3837
Epoch 319/500
800/800 [==============================] - 1s 1ms/step - loss: 1.5286 - val_loss: 0.5983
Epoch 320/500
800/800 [==============================] - 1s 1ms/step - loss: 1.0397 - val_loss: 1.0191
Epoch 321/500
800/800 [==============================] - 1s 1ms/step - loss: 1.4648 - val_loss: 7.7756
Epoch 322/500
800/800 [==============================] - 1s 1ms/step - loss: 3.6709 - val_loss: 0.5757
Epoch 323/500
800/800 [==============================] - 1s 1ms/step - loss: 2.7581 - val_loss: 1.7740
Epoch 324/500
800/800 [==============================] - 1s 1ms/step - loss: 0.7954 - val_loss: 1.6186
Epoch 325/500
800/800 [==============================] - 1s 1ms/step - loss: 0.7867 - v

800/800 [==============================] - 1s 1ms/step - loss: 0.6958 - val_loss: 0.8957
Epoch 475/500
800/800 [==============================] - 1s 1ms/step - loss: 0.7837 - val_loss: 0.3788
Epoch 476/500
800/800 [==============================] - 1s 1ms/step - loss: 0.3726 - val_loss: 0.1613
Epoch 477/500
800/800 [==============================] - 1s 1ms/step - loss: 5.7300 - val_loss: 8.9538
Epoch 478/500
800/800 [==============================] - 1s 1ms/step - loss: 4.1177 - val_loss: 0.6416
Epoch 479/500
800/800 [==============================] - 1s 1ms/step - loss: 0.9832 - val_loss: 0.5914
Epoch 480/500
800/800 [==============================] - 1s 1ms/step - loss: 0.5196 - val_loss: 0.8666
Epoch 481/500
800/800 [==============================] - 1s 1ms/step - loss: 0.6631 - val_loss: 1.3690
Epoch 482/500
800/800 [==============================] - 1s 1ms/step - loss: 0.3901 - val_loss: 0.2155
Epoch 483/500
800/800 [==============================] - 1s 1ms/step - loss: 0.5248 - v

### Many to One with Multiple features

In [ ]:
X1 = np.array([x+3 for x in range(0, 135, 3)])
print(X1)

X2 = np.array([x+5 for x in range(0, 225, 5)])
print(X2)

[  3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48  51  54
  57  60  63  66  69  72  75  78  81  84  87  90  93  96  99 102 105 108
 111 114 117 120 123 126 129 132 135]
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180
 185 190 195 200 205 210 215 220 225]


In [ ]:
X1.shape

(45,)

In [ ]:
X1= X1.reshape(-1,1)

In [ ]:
X2=X2.reshape(-1,1)

In [ ]:
X= np.concatenate((X1,X2), axis=1)

In [ ]:
X.shape

(45, 2)

In [ ]:
X = array(X).reshape(15, 3, 2)
print(X)

[[[  3   5]
  [  6  10]
  [  9  15]]

 [[ 12  20]
  [ 15  25]
  [ 18  30]]

 [[ 21  35]
  [ 24  40]
  [ 27  45]]

 [[ 30  50]
  [ 33  55]
  [ 36  60]]

 [[ 39  65]
  [ 42  70]
  [ 45  75]]

 [[ 48  80]
  [ 51  85]
  [ 54  90]]

 [[ 57  95]
  [ 60 100]
  [ 63 105]]

 [[ 66 110]
  [ 69 115]
  [ 72 120]]

 [[ 75 125]
  [ 78 130]
  [ 81 135]]

 [[ 84 140]
  [ 87 145]
  [ 90 150]]

 [[ 93 155]
  [ 96 160]
  [ 99 165]]

 [[102 170]
  [105 175]
  [108 180]]

 [[111 185]
  [114 190]
  [117 195]]

 [[120 200]
  [123 205]
  [126 210]]

 [[129 215]
  [132 220]
  [135 225]]]


In [ ]:
y=list()

In [ ]:
for x in X:
    print(x)
    y.append( x[2,0]*3 + x[2,1]*2)

[[ 3  5]
 [ 6 10]
 [ 9 15]]
[[12 20]
 [15 25]
 [18 30]]
[[21 35]
 [24 40]
 [27 45]]
[[30 50]
 [33 55]
 [36 60]]
[[39 65]
 [42 70]
 [45 75]]
[[48 80]
 [51 85]
 [54 90]]
[[ 57  95]
 [ 60 100]
 [ 63 105]]
[[ 66 110]
 [ 69 115]
 [ 72 120]]
[[ 75 125]
 [ 78 130]
 [ 81 135]]
[[ 84 140]
 [ 87 145]
 [ 90 150]]
[[ 93 155]
 [ 96 160]
 [ 99 165]]
[[102 170]
 [105 175]
 [108 180]]
[[111 185]
 [114 190]
 [117 195]]
[[120 200]
 [123 205]
 [126 210]]
[[129 215]
 [132 220]
 [135 225]]


In [ ]:
y=np.array(y)

In [ ]:
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(3, 2)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
history = model.fit(X, y, epochs=1000, validation_split=0.2, verbose=1)

Train on 12 samples, validate on 3 samples
Epoch 1/1000
12/12 [==============================] - 1s 64ms/step - loss: 166755.3594 - val_loss: 604987.8125
Epoch 2/1000
12/12 [==============================] - 0s 1ms/step - loss: 165835.2344 - val_loss: 600003.3750
Epoch 3/1000
12/12 [==============================] - 0s 666us/step - loss: 164425.8281 - val_loss: 594288.4375
Epoch 4/1000
12/12 [==============================] - 0s 666us/step - loss: 162914.7188 - val_loss: 587300.2500
Epoch 5/1000
12/12 [==============================] - 0s 666us/step - loss: 161101.6406 - val_loss: 578545.1875
Epoch 6/1000
12/12 [==============================] - 0s 666us/step - loss: 158943.2656 - val_loss: 567153.1875
Epoch 7/1000
12/12 [==============================] - 0s 666us/step - loss: 156391.2031 - val_loss: 553553.1875
Epoch 8/1000
12/12 [==============================] - 0s 666us/step - loss: 153467.0938 - val_loss: 539737.3125
Epoch 9/1000
12/12 [==============================] - 0s 666us/s

Epoch 75/1000
12/12 [==============================] - 0s 845us/step - loss: 268.2394 - val_loss: 30.7069
Epoch 76/1000
12/12 [==============================] - 0s 893us/step - loss: 268.2782 - val_loss: 46.6804
Epoch 77/1000
12/12 [==============================] - 0s 904us/step - loss: 263.4707 - val_loss: 105.6499
Epoch 78/1000
12/12 [==============================] - 0s 810us/step - loss: 258.1294 - val_loss: 140.9591
Epoch 79/1000
12/12 [==============================] - 0s 840us/step - loss: 252.4054 - val_loss: 187.4275
Epoch 80/1000
12/12 [==============================] - 0s 666us/step - loss: 246.7559 - val_loss: 141.2772
Epoch 81/1000
12/12 [==============================] - 0s 1ms/step - loss: 234.4062 - val_loss: 78.7322
Epoch 82/1000
12/12 [==============================] - 0s 666us/step - loss: 219.0118 - val_loss: 42.4857
Epoch 83/1000
12/12 [==============================] - 0s 666us/step - loss: 204.0028 - val_loss: 34.4081
Epoch 84/1000
12/12 [=======================

Epoch 153/1000
12/12 [==============================] - 0s 666us/step - loss: 30.8071 - val_loss: 8.3089
Epoch 154/1000
12/12 [==============================] - 0s 667us/step - loss: 30.4070 - val_loss: 4.0172
Epoch 155/1000
12/12 [==============================] - 0s 666us/step - loss: 29.8626 - val_loss: 3.1125
Epoch 156/1000
12/12 [==============================] - 0s 666us/step - loss: 29.4405 - val_loss: 7.2458
Epoch 157/1000
12/12 [==============================] - 0s 666us/step - loss: 28.9276 - val_loss: 9.1217
Epoch 158/1000
12/12 [==============================] - 0s 667us/step - loss: 28.5045 - val_loss: 5.3261
Epoch 159/1000
12/12 [==============================] - 0s 666us/step - loss: 28.0785 - val_loss: 5.6489
Epoch 160/1000
12/12 [==============================] - 0s 666us/step - loss: 27.6689 - val_loss: 9.7181
Epoch 161/1000
12/12 [==============================] - 0s 1ms/step - loss: 27.2608 - val_loss: 8.9320
Epoch 162/1000
12/12 [==============================] - 0

Epoch 232/1000
12/12 [==============================] - 0s 666us/step - loss: 5.9807 - val_loss: 4.4374
Epoch 233/1000
12/12 [==============================] - 0s 667us/step - loss: 5.7960 - val_loss: 3.6088
Epoch 234/1000
12/12 [==============================] - 0s 666us/step - loss: 5.6153 - val_loss: 4.1369
Epoch 235/1000
12/12 [==============================] - 0s 666us/step - loss: 5.4308 - val_loss: 4.6580
Epoch 236/1000
12/12 [==============================] - 0s 1ms/step - loss: 5.2598 - val_loss: 3.5754
Epoch 237/1000
12/12 [==============================] - 0s 666us/step - loss: 5.0865 - val_loss: 3.9858
Epoch 238/1000
12/12 [==============================] - 0s 1ms/step - loss: 4.9138 - val_loss: 4.4416
Epoch 239/1000
12/12 [==============================] - 0s 666us/step - loss: 4.7517 - val_loss: 3.7951
Epoch 240/1000
12/12 [==============================] - 0s 1ms/step - loss: 4.5882 - val_loss: 4.0686
Epoch 241/1000
12/12 [==============================] - 0s 667us/step 

Epoch 312/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.3619 - val_loss: 4.8198
Epoch 313/1000
12/12 [==============================] - 0s 666us/step - loss: 0.3547 - val_loss: 5.0370
Epoch 314/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.3476 - val_loss: 4.9507
Epoch 315/1000
12/12 [==============================] - 0s 666us/step - loss: 0.3408 - val_loss: 4.8472
Epoch 316/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.3346 - val_loss: 5.1008
Epoch 317/1000
12/12 [==============================] - 0s 982us/step - loss: 0.3289 - val_loss: 4.7539
Epoch 318/1000
12/12 [==============================] - 0s 716us/step - loss: 0.3232 - val_loss: 5.1120
Epoch 319/1000
12/12 [==============================] - 0s 795us/step - loss: 0.3174 - val_loss: 4.9534
Epoch 320/1000
12/12 [==============================] - 0s 796us/step - loss: 0.3118 - val_loss: 4.9161
Epoch 321/1000
12/12 [==============================] - 0s 347us/step 

Epoch 392/1000
12/12 [==============================] - 0s 666us/step - loss: 0.1464 - val_loss: 3.6722
Epoch 393/1000
12/12 [==============================] - 0s 669us/step - loss: 0.1511 - val_loss: 4.8995
Epoch 394/1000
12/12 [==============================] - 0s 663us/step - loss: 0.1518 - val_loss: 3.9369
Epoch 395/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.1428 - val_loss: 3.8332
Epoch 396/1000
12/12 [==============================] - 0s 667us/step - loss: 0.1422 - val_loss: 4.7881
Epoch 397/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.1453 - val_loss: 3.7266
Epoch 398/1000
12/12 [==============================] - 0s 666us/step - loss: 0.1402 - val_loss: 4.0894
Epoch 399/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.1352 - val_loss: 4.5574
Epoch 400/1000
12/12 [==============================] - 0s 665us/step - loss: 0.1373 - val_loss: 3.5412
Epoch 401/1000
12/12 [==============================] - 0s 1ms/step - 

Epoch 472/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0323 - val_loss: 1.1877
Epoch 473/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0302 - val_loss: 1.2089
Epoch 474/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0290 - val_loss: 1.3135
Epoch 475/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0290 - val_loss: 1.0619
Epoch 476/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0290 - val_loss: 1.2986
Epoch 477/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0281 - val_loss: 1.0698
Epoch 478/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0266 - val_loss: 1.1443
Epoch 479/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0254 - val_loss: 1.1357
Epoch 480/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0248 - val_loss: 0.9925
Epoch 481/1000
12/12 [==============================] - 0s 666us/ste

12/12 [==============================] - 0s 666us/step - loss: 0.0081 - val_loss: 0.6487
Epoch 552/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0083 - val_loss: 0.5668
Epoch 553/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0083 - val_loss: 0.6364
Epoch 554/1000
12/12 [==============================] - 0s 667us/step - loss: 0.0080 - val_loss: 0.6099
Epoch 555/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0077 - val_loss: 0.5771
Epoch 556/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0078 - val_loss: 0.6403
Epoch 557/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0079 - val_loss: 0.5720
Epoch 558/1000
12/12 [==============================] - 0s 667us/step - loss: 0.0077 - val_loss: 0.5984
Epoch 559/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0074 - val_loss: 0.6070
Epoch 560/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0074 

Epoch 631/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0066 - val_loss: 1.2544
Epoch 632/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0306 - val_loss: 0.4478
Epoch 633/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0491 - val_loss: 1.1203
Epoch 634/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0125 - val_loss: 1.2280
Epoch 635/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0179 - val_loss: 0.5531
Epoch 636/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0370 - val_loss: 1.1137
Epoch 637/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0114 - val_loss: 1.1391
Epoch 638/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0140 - val_loss: 0.5696
Epoch 639/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0272 - val_loss: 0.9774
Epoch 640/1000
12/12 [==============================] - 0s 666us

12/12 [==============================] - 0s 716us/step - loss: 0.0045 - val_loss: 0.6765
Epoch 711/1000
12/12 [==============================] - 0s 805us/step - loss: 0.0045 - val_loss: 0.6873
Epoch 712/1000
12/12 [==============================] - 0s 708us/step - loss: 0.0045 - val_loss: 0.6839
Epoch 713/1000
12/12 [==============================] - 0s 173us/step - loss: 0.0044 - val_loss: 0.6740
Epoch 714/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0044 - val_loss: 0.6841
Epoch 715/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0044 - val_loss: 0.6767
Epoch 716/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0044 - val_loss: 0.6718
Epoch 717/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0044 - val_loss: 0.6802
Epoch 718/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0044 - val_loss: 0.6710
Epoch 719/1000
12/12 [==============================] - 0s 666us/step - loss: 0.004

Epoch 790/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0037 - val_loss: 0.6385
Epoch 791/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0037 - val_loss: 0.6388
Epoch 792/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0037 - val_loss: 0.6375
Epoch 793/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0037 - val_loss: 0.6378
Epoch 794/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0037 - val_loss: 0.6369
Epoch 795/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0037 - val_loss: 0.6363
Epoch 796/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0037 - val_loss: 0.6365
Epoch 797/1000
12/12 [==============================] - 0s 667us/step - loss: 0.0037 - val_loss: 0.6346
Epoch 798/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0037 - val_loss: 0.6358
Epoch 799/1000
12/12 [==============================] - 0s 666us/s

Epoch 870/1000
12/12 [==============================] - 0s 786us/step - loss: 0.0251 - val_loss: 0.9850
Epoch 871/1000
12/12 [==============================] - 0s 792us/step - loss: 0.0069 - val_loss: 1.4844
Epoch 872/1000
12/12 [==============================] - 0s 667us/step - loss: 0.0307 - val_loss: 0.7860
Epoch 873/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0156 - val_loss: 0.8644
Epoch 874/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0091 - val_loss: 1.3894
Epoch 875/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0247 - val_loss: 0.8740
Epoch 876/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0088 - val_loss: 0.8608
Epoch 877/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0105 - val_loss: 1.3751
Epoch 878/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0186 - val_loss: 0.9926
Epoch 879/1000
12/12 [==============================] - 0s 1ms/ste

Epoch 950/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0036 - val_loss: 0.7435
Epoch 951/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0036 - val_loss: 0.7404
Epoch 952/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0036 - val_loss: 0.7489
Epoch 953/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0036 - val_loss: 0.7410
Epoch 954/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0036 - val_loss: 0.7409
Epoch 955/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0036 - val_loss: 0.7471
Epoch 956/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0036 - val_loss: 0.7394
Epoch 957/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0035 - val_loss: 0.7408
Epoch 958/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0035 - val_loss: 0.7445
Epoch 959/1000
12/12 [==============================] - 0s 666us/step 

In [ ]:
model.predict(np.array( [[[120, 200],
  [123, 205],
  [100, 210]]]))

array([[788.6328]], dtype=float32)

## Bidirectional LSTM 

In [ ]:
from keras.layers import Bidirectional

model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(3, 2)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1)
test_output = model.predict(test_input, verbose=0)
print(test_output)

Train on 12 samples, validate on 3 samples
Epoch 1/1000
12/12 [==============================] - 2s 144ms/step - loss: 3505.6660 - val_loss: 12908.0225
Epoch 2/1000
12/12 [==============================] - 0s 664us/step - loss: 3405.7168 - val_loss: 12481.5732
Epoch 3/1000
12/12 [==============================] - 0s 666us/step - loss: 3291.6238 - val_loss: 12029.4141
Epoch 4/1000
12/12 [==============================] - 0s 666us/step - loss: 3171.7791 - val_loss: 11534.6875
Epoch 5/1000
12/12 [==============================] - 0s 666us/step - loss: 3040.9434 - val_loss: 11066.3662
Epoch 6/1000
12/12 [==============================] - 0s 666us/step - loss: 2916.4358 - val_loss: 10595.4883
Epoch 7/1000
12/12 [==============================] - 0s 667us/step - loss: 2790.6465 - val_loss: 10103.8291
Epoch 8/1000
12/12 [==============================] - 0s 665us/step - loss: 2660.8083 - val_loss: 9601.9902
Epoch 9/1000
12/12 [==============================] - 0s 666us/step - loss: 2533.3135 

Epoch 79/1000
12/12 [==============================] - 0s 666us/step - loss: 0.2048 - val_loss: 3.6454
Epoch 80/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.2117 - val_loss: 4.2288
Epoch 81/1000
12/12 [==============================] - 0s 666us/step - loss: 0.2287 - val_loss: 4.7207
Epoch 82/1000
12/12 [==============================] - 0s 666us/step - loss: 0.2497 - val_loss: 5.0990
Epoch 83/1000
12/12 [==============================] - 0s 666us/step - loss: 0.2699 - val_loss: 5.3429
Epoch 84/1000
12/12 [==============================] - 0s 667us/step - loss: 0.2850 - val_loss: 5.4451
Epoch 85/1000
12/12 [==============================] - 0s 666us/step - loss: 0.2926 - val_loss: 5.4086
Epoch 86/1000
12/12 [==============================] - 0s 666us/step - loss: 0.2916 - val_loss: 5.2454
Epoch 87/1000
12/12 [==============================] - 0s 666us/step - loss: 0.2824 - val_loss: 4.9747
Epoch 88/1000
12/12 [==============================] - 0s 666us/step - loss

Epoch 159/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0184 - val_loss: 0.2197
Epoch 160/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0180 - val_loss: 0.2078
Epoch 161/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0176 - val_loss: 0.1965
Epoch 162/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0172 - val_loss: 0.1858
Epoch 163/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0169 - val_loss: 0.1758
Epoch 164/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0166 - val_loss: 0.1664
Epoch 165/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0163 - val_loss: 0.1578
Epoch 166/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0160 - val_loss: 0.1498
Epoch 167/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0157 - val_loss: 0.1425
Epoch 168/1000
12/12 [==============================] - 0s 666us/ste

Epoch 238/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0072 - val_loss: 0.0119
Epoch 239/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0071 - val_loss: 0.0115
Epoch 240/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0071 - val_loss: 0.0112
Epoch 241/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0070 - val_loss: 0.0109
Epoch 242/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0070 - val_loss: 0.0107
Epoch 243/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0070 - val_loss: 0.0104
Epoch 244/1000
12/12 [==============================] - 0s 667us/step - loss: 0.0069 - val_loss: 0.0101
Epoch 245/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0069 - val_loss: 0.0099
Epoch 246/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0068 - val_loss: 0.0096
Epoch 247/1000
12/12 [==============================] - 0s 666us/ste

Epoch 317/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0048 - val_loss: 0.0016
Epoch 318/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0048 - val_loss: 0.0016
Epoch 319/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0048 - val_loss: 0.0015
Epoch 320/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0047 - val_loss: 0.0015
Epoch 321/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0047 - val_loss: 0.0014
Epoch 322/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0047 - val_loss: 0.0014
Epoch 323/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0047 - val_loss: 0.0013
Epoch 324/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0047 - val_loss: 0.0013
Epoch 325/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0046 - val_loss: 0.0013
Epoch 326/1000
12/12 [==============================] - 0s 666us/s

Epoch 394/1000
12/12 [==============================] - 0s 667us/step - loss: 0.0035 - val_loss: 9.6816e-05
Epoch 395/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0035 - val_loss: 9.8164e-05
Epoch 396/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0035 - val_loss: 9.9832e-05
Epoch 397/1000
12/12 [==============================] - 0s 697us/step - loss: 0.0035 - val_loss: 1.0216e-04
Epoch 398/1000
12/12 [==============================] - 0s 811us/step - loss: 0.0034 - val_loss: 1.0483e-04
Epoch 399/1000
12/12 [==============================] - 0s 819us/step - loss: 0.0034 - val_loss: 1.0751e-04
Epoch 400/1000
12/12 [==============================] - 0s 712us/step - loss: 0.0034 - val_loss: 1.1089e-04
Epoch 401/1000
12/12 [==============================] - 0s 787us/step - loss: 0.0034 - val_loss: 1.1472e-04
Epoch 402/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0034 - val_loss: 1.1885e-04
Epoch 403/1000
12/12 [======

Epoch 471/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0025 - val_loss: 0.0012
Epoch 472/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0025 - val_loss: 0.0012
Epoch 473/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0025 - val_loss: 0.0012
Epoch 474/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0025 - val_loss: 0.0013
Epoch 475/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0025 - val_loss: 0.0013
Epoch 476/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0025 - val_loss: 0.0013
Epoch 477/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0025 - val_loss: 0.0013
Epoch 478/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0025 - val_loss: 0.0014
Epoch 479/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0025 - val_loss: 0.0014
Epoch 480/1000
12/12 [==============================] - 0s 666us

Epoch 550/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0019 - val_loss: 0.0035
Epoch 551/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0019 - val_loss: 0.0036
Epoch 552/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0019 - val_loss: 0.0036
Epoch 553/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0018 - val_loss: 0.0036
Epoch 554/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0018 - val_loss: 0.0037
Epoch 555/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0018 - val_loss: 0.0037
Epoch 556/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0018 - val_loss: 0.0037
Epoch 557/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0018 - val_loss: 0.0038
Epoch 558/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0018 - val_loss: 0.0038
Epoch 559/1000
12/12 [==============================] - 0s 666us/s

Epoch 629/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0014 - val_loss: 0.0059
Epoch 630/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0014 - val_loss: 0.0059
Epoch 631/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0014 - val_loss: 0.0059
Epoch 632/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0014 - val_loss: 0.0059
Epoch 633/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0014 - val_loss: 0.0059
Epoch 634/1000
12/12 [==============================] - 0s 667us/step - loss: 0.0014 - val_loss: 0.0060
Epoch 635/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0014 - val_loss: 0.0060
Epoch 636/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0014 - val_loss: 0.0060
Epoch 637/1000
12/12 [==============================] - 0s 667us/step - loss: 0.0014 - val_loss: 0.0060
Epoch 638/1000
12/12 [==============================] - 0s 666us/s

Epoch 708/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0011 - val_loss: 0.0071
Epoch 709/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0011 - val_loss: 0.0071
Epoch 710/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0011 - val_loss: 0.0071
Epoch 711/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0011 - val_loss: 0.0071
Epoch 712/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0011 - val_loss: 0.0071
Epoch 713/1000
12/12 [==============================] - 0s 667us/step - loss: 0.0011 - val_loss: 0.0072
Epoch 714/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0011 - val_loss: 0.0072
Epoch 715/1000
12/12 [==============================] - 0s 667us/step - loss: 0.0011 - val_loss: 0.0072
Epoch 716/1000
12/12 [==============================] - 0s 666us/step - loss: 0.0011 - val_loss: 0.0072
Epoch 717/1000
12/12 [==============================] - 0s 666us

Epoch 787/1000
12/12 [==============================] - 0s 666us/step - loss: 9.5330e-04 - val_loss: 0.0071
Epoch 788/1000
12/12 [==============================] - 0s 666us/step - loss: 9.5126e-04 - val_loss: 0.0071
Epoch 789/1000
12/12 [==============================] - 0s 667us/step - loss: 9.4918e-04 - val_loss: 0.0071
Epoch 790/1000
12/12 [==============================] - 0s 666us/step - loss: 9.4727e-04 - val_loss: 0.0071
Epoch 791/1000
12/12 [==============================] - 0s 666us/step - loss: 9.4522e-04 - val_loss: 0.0071
Epoch 792/1000
12/12 [==============================] - 0s 666us/step - loss: 9.4322e-04 - val_loss: 0.0071
Epoch 793/1000
12/12 [==============================] - 0s 666us/step - loss: 9.4125e-04 - val_loss: 0.0071
Epoch 794/1000
12/12 [==============================] - 0s 1ms/step - loss: 9.3926e-04 - val_loss: 0.0071
Epoch 795/1000
12/12 [==============================] - 0s 666us/step - loss: 9.3722e-04 - val_loss: 0.0071
Epoch 796/1000
12/12 [========

Epoch 864/1000
12/12 [==============================] - 0s 666us/step - loss: 8.1384e-04 - val_loss: 0.0063
Epoch 865/1000
12/12 [==============================] - 0s 666us/step - loss: 8.1219e-04 - val_loss: 0.0063
Epoch 866/1000
12/12 [==============================] - 0s 667us/step - loss: 8.1059e-04 - val_loss: 0.0063
Epoch 867/1000
12/12 [==============================] - 0s 666us/step - loss: 8.0885e-04 - val_loss: 0.0063
Epoch 868/1000
12/12 [==============================] - 0s 1ms/step - loss: 8.0734e-04 - val_loss: 0.0063
Epoch 869/1000
12/12 [==============================] - 0s 666us/step - loss: 8.0567e-04 - val_loss: 0.0062
Epoch 870/1000
12/12 [==============================] - 0s 666us/step - loss: 8.0406e-04 - val_loss: 0.0062
Epoch 871/1000
12/12 [==============================] - 0s 1ms/step - loss: 8.0252e-04 - val_loss: 0.0062
Epoch 872/1000
12/12 [==============================] - 0s 666us/step - loss: 8.0081e-04 - val_loss: 0.0062
Epoch 873/1000
12/12 [==========

12/12 [==============================] - 0s 1ms/step - loss: 6.9804e-04 - val_loss: 0.0051
Epoch 941/1000
12/12 [==============================] - 0s 666us/step - loss: 6.9666e-04 - val_loss: 0.0051
Epoch 942/1000
12/12 [==============================] - 0s 666us/step - loss: 6.9526e-04 - val_loss: 0.0051
Epoch 943/1000
12/12 [==============================] - 0s 666us/step - loss: 6.9381e-04 - val_loss: 0.0050
Epoch 944/1000
12/12 [==============================] - 0s 559us/step - loss: 6.9241e-04 - val_loss: 0.0050
Epoch 945/1000
12/12 [==============================] - 0s 666us/step - loss: 6.9095e-04 - val_loss: 0.0050
Epoch 946/1000
12/12 [==============================] - 0s 1ms/step - loss: 6.8960e-04 - val_loss: 0.0050
Epoch 947/1000
12/12 [==============================] - 0s 666us/step - loss: 6.8818e-04 - val_loss: 0.0050
Epoch 948/1000
12/12 [==============================] - 0s 1ms/step - loss: 6.8677e-04 - val_loss: 0.0050
Epoch 949/1000
12/12 [===========================

NameError: name 'test_input' is not defined

In [ ]:
model.summary()

Model: "sequential_19"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bidirectional_1 (Bidirection (None, 100)               21200     
_________________________________________________________________
dense_28 (Dense)             (None, 1)                 101       
Total params: 21,301
Trainable params: 21,301
Non-trainable params: 0
_________________________________________________________________


In [ ]:
inputs = tf.random.normal([32, 10, 8])
lstm = tf.keras.layers.LSTM(1)
output = lstm(inputs)
print(output.shape)

lstm = tf.keras.layers.LSTM(1, return_sequences=True, return_state=True)
whole_seq_output, final_memory_state, final_carry_state = lstm(inputs)
print(whole_seq_output.shape)

print(final_memory_state.shape)

print(final_carry_state.shape)


(32, 1)
(32, 10, 1)
(32, 1)
(32, 1)


In [ ]:
from keras.preprocessing import sequence 
from keras.models import Sequential 
from keras.layers import Dense, Embedding 
from keras.layers import LSTM 
from keras.datasets import imdb

In [ ]:
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words = 2000)


In [ ]:
x_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 2,
 66,
 2,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 2,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 2,
 336,
 385,
 39,
 4,
 172,
 2,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2,
 19,
 14,
 22,
 4,
 1920,
 2,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 2,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2,
 2,
 16,
 480,
 66,
 2,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 2,
 8,
 4,
 107,
 117,
 2,
 15,
 256,
 4,
 2,
 7,
 2,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 2,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2,
 56,
 26,
 141,
 6,
 194,
 2,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5,
 144,
 30,
 2,
 18,
 51,
 36,
 28,
 224,
 92,
 25,
 104,
 

In [ ]:
x_train = sequence.pad_sequences(x_train, maxlen=80) 
x_test = sequence.pad_sequences(x_test, maxlen=80)

In [ ]:
model = Sequential() 
model.add(Embedding(2000, 128)) 
model.add(LSTM(128, dropout = 0.2, recurrent_dropout = 0.2)) 
model.add(Dense(1, activation = 'sigmoid'))

In [ ]:
model.compile(loss = 'binary_crossentropy', 
   optimizer = 'adam', metrics = ['accuracy'])

In [ ]:
model.fit(
   x_train, y_train, 
   batch_size = 32, 
   epochs = 15, 
   validation_data = (x_test, y_test)
)

C:\Users\Asus\Anaconda3\lib\site-packages\tensorflow\python\framework\indexed_slices.py:434: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 25000 samples, validate on 25000 samples
Epoch 1/15
24992/25000 [============================>.] - ETA: 0s - loss: 0.4821 - accuracy: 0.7668

KeyboardInterrupt: 