<a href="https://colab.research.google.com/github/vijjipammi/pub/blob/main/pytorch_basics_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401 unused import
from matplotlib import cm
import torch

### Create a Simple Torch Tensor

In [ ]:
tensor_x = torch.tensor([[2,3,4],[3,4,5],[6,7,8],[9,10,11]])

In [ ]:
print(tensor_x)

tensor([[ 2,  3,  4],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


In [ ]:
print(tensor_x[:,0])

tensor([2, 3, 6, 9])


In [ ]:
print(tensor_x[:,0:2])

tensor([[ 2,  3],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10]])


In [ ]:
tensor_x.shape

torch.Size([4, 3])

### Reshape Torch Tensor

In [ ]:
tensor_x.view(1,-1)

tensor([[ 2,  3,  4,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [ ]:
tensor_x.view(3,4)

tensor([[ 2,  3,  4,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
tensor_x.view(2,6)

tensor([[ 2,  3,  4,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [ ]:
tensor_x.view(-1,1)

tensor([[ 2],
        [ 3],
        [ 4],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]])

### Torch.ones and Torch.zeros

In [ ]:
tensor_x=torch.ones(5,8)

In [ ]:
tensor_y=torch.ones(5,8)

In [ ]:
tensor_z=tensor_x+tensor_y

In [ ]:
print(tensor_z)

tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]])


In [ ]:
tensor_p=torch.ones(8,9)

In [ ]:
tensor_p

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
print(tensor_p.shape)

torch.Size([8, 9])


### Convert to Numpy Array

In [ ]:
numpy_array=tensor_p.numpy()

In [ ]:
numpy_array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

In [ ]:
type(tensor_p)

torch.Tensor

In [ ]:
type(numpy_array)

numpy.ndarray

### Torch Tensor from Numpy Array

In [ ]:
numpy_array= np.random.randn(5,4)

In [ ]:
print(numpy_array)

[[-0.40870136 -0.71062856 -2.26935611  0.99657885]
 [-0.23670254 -0.83968899  0.07879434  1.86393124]
 [-0.98096182  0.3536719  -0.78969563 -0.69098981]
 [-0.477626   -1.87120472 -1.79050436  0.868673  ]
 [-1.24459862  0.52041629  0.8868762  -1.96251989]]


In [ ]:
tensor_e=torch.from_numpy(numpy_array)

In [ ]:
print(tensor_e)

tensor([[-0.4087, -0.7106, -2.2694,  0.9966],
        [-0.2367, -0.8397,  0.0788,  1.8639],
        [-0.9810,  0.3537, -0.7897, -0.6910],
        [-0.4776, -1.8712, -1.7905,  0.8687],
        [-1.2446,  0.5204,  0.8869, -1.9625]], dtype=torch.float64)


In [ ]:
type(tensor_e)

torch.Tensor

### Squeeze Dimensions

In [ ]:
tensor_f=tensor_e.unsqueeze(dim=0)

In [ ]:
tensor_f.shape

torch.Size([1, 5, 4])

In [ ]:
tensor_g=tensor_f.unsqueeze(dim=0)

In [ ]:
tensor_g.shape

torch.Size([1, 1, 5, 4])

In [ ]:
tensor_h=tensor_g.squeeze(dim=0)

In [ ]:
tensor_h.shape

torch.Size([1, 5, 4])

In [ ]:
tensor_i=tensor_h.squeeze(dim=0)

### Compare Multiplication of Numpy and Torch Tensors

In [ ]:
%%time
a=np.random.randn(2000,2000)
b=np.random.randn(2000,2000)
c=np.matmul(a,b)

CPU times: user 1.07 s, sys: 30.2 ms, total: 1.1 s
Wall time: 724 ms


In [ ]:
%%time
a=torch.randn([2000,2000])
b=torch.randn([2000,2000])

c=torch.matmul(a,b)

CPU times: user 270 ms, sys: 7.3 ms, total: 277 ms
Wall time: 307 ms


### Gradients in Pytorch

In [ ]:
x = torch.ones(3,2, requires_grad=True)

In [ ]:
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [ ]:
y=x+5

In [ ]:
print(y)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [ ]:
z=y*y+7

In [ ]:
print(z)

tensor([[43., 43.],
        [43., 43.],
        [43., 43.]], grad_fn=<AddBackward0>)


In [ ]:
t=torch.sum(z)

In [ ]:
t.backward()

In [ ]:
print(t)

tensor(258., grad_fn=<SumBackward0>)


In [ ]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


In [ ]:
print(y.grad)

None


In [ ]:
print(z.grad)

None


## Regression using Pytorch Gradients

In [ ]:
x = torch.randn(4,5, requires_grad=True)

In [ ]:
x.shape

torch.Size([4, 5])

In [ ]:
y=1.4*x*x*x+140*x*x+14*x+14

In [ ]:
y[0][0]

tensor(161.5319, grad_fn=<SelectBackward>)

In [ ]:
w0 = torch.tensor([1.0], requires_grad=True)

In [ ]:
w1 = torch.tensor([1.0], requires_grad=True)

In [ ]:
w2 = torch.tensor([1.0], requires_grad=True)

In [ ]:
b = torch.tensor([1.0], requires_grad=True)

In [ ]:
y_hat = w0*x*x*x+w1*x*x+w2*x+b

In [ ]:
loss = torch.sum((y_hat -y)**2)

In [ ]:
print(loss)

tensor(466894.8438, grad_fn=<SumBackward0>)


In [ ]:
loss.backward(retain_graph=True)

In [ ]:
print(w1.grad, w2.grad, b.grad)

tensor([-6179.9692]) tensor([-1124.2550]) tensor([-4531.7856])


In [ ]:
learning_rate=0.0009

for i in range (1, 3000):
    y_hat = w0*x*x*x+w1*x*x+w2*x+b
    loss = torch.sum((y_hat -y)**2)
    loss.backward(retain_graph=True)
    with torch.no_grad():
        w0 -= w0.grad*(learning_rate)
        w1 -= w1.grad*(learning_rate)
        w2 -= w2.grad*(learning_rate)
        b -= b.grad*(learning_rate)
        w0.grad.zero_()

        w1.grad.zero_()
        w2.grad.zero_()
        b.grad.zero_()
        print(w0,w1, w2, b)

tensor([6.6042], requires_grad=True) tensor([12.1239], requires_grad=True) tensor([3.0237], requires_grad=True) tensor([9.1572], requires_grad=True)
tensor([8.7191], requires_grad=True) tensor([16.9624], requires_grad=True) tensor([3.7179], requires_grad=True) tensor([12.6265], requires_grad=True)
tensor([10.5651], requires_grad=True) tensor([21.4943], requires_grad=True) tensor([4.2909], requires_grad=True) tensor([15.8351], requires_grad=True)
tensor([12.1718], requires_grad=True) tensor([25.7425], requires_grad=True) tensor([4.7573], requires_grad=True) tensor([18.8019], requires_grad=True)
tensor([13.5658], requires_grad=True) tensor([29.7284], requires_grad=True) tensor([5.1303], requires_grad=True) tensor([21.5439], requires_grad=True)
tensor([14.7707], requires_grad=True) tensor([33.4711], requires_grad=True) tensor([5.4215], requires_grad=True) tensor([24.0773], requires_grad=True)
tensor([15.8080], requires_grad=True) tensor([36.9887], requires_grad=True) tensor([5.6413], requ

## How Weights are Updated/Predicted in Neural Networks

In [ ]:
W = torch.tensor([[3.0,4.0,5.0],[6.0,7.0,8.0],[9.0,10.0,11.0]], requires_grad=True)

In [ ]:
W.grad

In [ ]:
b= torch.tensor([[10.0,10.0,10.0]])

In [ ]:
X = torch.randn([1000,3])

In [ ]:
X.shape

torch.Size([1000, 3])

In [ ]:
Y=torch.tensor([[]])

In [ ]:
for x in X:
    y=torch.matmul(W,x)+b
    print(y)
    Y=torch.cat((Y,y),dim=1)

tensor([[ 6.0552,  2.1934, -1.6685]], grad_fn=<AddBackward0>)
tensor([[10.4769, 11.4221, 12.3674]], grad_fn=<AddBackward0>)
tensor([[  1.4801,  -4.3035, -10.0872]], grad_fn=<AddBackward0>)
tensor([[8.8393, 8.8954, 8.9516]], grad_fn=<AddBackward0>)
tensor([[10.6285, 11.3592, 12.0899]], grad_fn=<AddBackward0>)
tensor([[  1.7502,  -4.6294, -11.0090]], grad_fn=<AddBackward0>)
tensor([[-7.2975e-03, -5.1611e+00, -1.0315e+01]], grad_fn=<AddBackward0>)
tensor([[10.7477, 11.6235, 12.4993]], grad_fn=<AddBackward0>)
tensor([[13.4540, 17.7870, 22.1200]], grad_fn=<AddBackward0>)
tensor([[ -3.3187, -13.8077, -24.2967]], grad_fn=<AddBackward0>)
tensor([[11.2206, 12.8602, 14.4998]], grad_fn=<AddBackward0>)
tensor([[13.3407, 16.0380, 18.7354]], grad_fn=<AddBackward0>)
tensor([[ -0.9984,  -9.1929, -17.3875]], grad_fn=<AddBackward0>)
tensor([[26.1103, 38.9468, 51.7833]], grad_fn=<AddBackward0>)
tensor([[6.6801, 4.6060, 2.5319]], grad_fn=<AddBackward0>)
tensor([[11.5267, 13.7788, 16.0308]], grad_fn=<AddBa

In [ ]:
Y=Y.view(1000,3)

In [ ]:
Y

tensor([[  6.0552,   2.1934,  -1.6685],
        [ 10.4769,  11.4221,  12.3674],
        [  1.4801,  -4.3035, -10.0872],
        ...,
        [ 12.0749,  13.7435,  15.4121],
        [ -3.2829, -12.3467, -21.4105],
        [  7.9996,   6.1989,   4.3982]], grad_fn=<ViewBackward>)

### Learn Weights from X and Y

In [ ]:
learning_rate=0.00001

W_hat=torch.tensor([[0.0,0.0,0.0],[0.0,0.0,0.0],[0.0,0.0,0.0]], requires_grad=True)
b_hat=torch.tensor([[0.0,0.0,0.0]], requires_grad=True)

for i in range(1000):

    Y_hat=torch.tensor([[]])
    for x in X:
        y_hat = torch.matmul(W_hat,x)+b_hat
        Y_hat=torch.cat((Y_hat,y_hat),dim=1)
    
    Y_hat=Y_hat.view(1000,3)

    loss = torch.sum((Y_hat -Y)**2)
    
    loss.backward(retain_graph=True)
    
    with torch.no_grad():
        W_hat     -= W_hat.grad*(learning_rate)
        b_hat     -= b_hat.grad*(learning_rate)
        W_hat.grad.zero_()
        b_hat.grad.zero_()
        print(W_hat, b_hat)

tensor([[0.0705, 0.0650, 0.0992],
        [0.1327, 0.1292, 0.1592],
        [0.1948, 0.1935, 0.2191]], requires_grad=True) tensor([[0.1942, 0.1903, 0.1864]], requires_grad=True)
tensor([[0.1394, 0.1290, 0.1964],
        [0.2624, 0.2561, 0.3152],
        [0.3854, 0.3832, 0.4339]], requires_grad=True) tensor([[0.3846, 0.3770, 0.3693]], requires_grad=True)
tensor([[0.2068, 0.1920, 0.2917],
        [0.3894, 0.3806, 0.4681],
        [0.5719, 0.5692, 0.6444]], requires_grad=True) tensor([[0.5713, 0.5601, 0.5488]], requires_grad=True)
tensor([[0.2726, 0.2540, 0.3851],
        [0.5135, 0.5028, 0.6179],
        [0.7545, 0.7516, 0.8507]], requires_grad=True) tensor([[0.7543, 0.7396, 0.7250]], requires_grad=True)
tensor([[0.3369, 0.3151, 0.4767],
        [0.6350, 0.6227, 0.7648],
        [0.9331, 0.9304, 1.0528]], requires_grad=True) tensor([[0.9337, 0.9158, 0.8979]], requires_grad=True)
tensor([[0.3998, 0.3752, 0.5664],
        [0.7538, 0.7405, 0.9087],
        [1.1079, 1.1057, 1.2510]], require