<a href="https://colab.research.google.com/github/vijjipammi/pub/blob/main/pytorch_basics_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Import Standard Pytorch Imports

In [ ]:
import torch
import torch.optim as optim
from torch.nn import Linear, MSELoss, functional as F
import numpy as np

### Create Data, X and y

In [ ]:
X= np.linspace(1,20,1000)

In [ ]:
y = 3*X*X + 5

In [ ]:
X.shape

(1000, 1)

In [ ]:
y.shape

(1000, 1)

In [ ]:
X =X.reshape(-1,1)
y=y.reshape(-1,1)

In [ ]:
X.shape

(1000, 1)

In [ ]:
y.shape

(1000, 1)

### Split Test and Train Data

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size =0.2, shuffle=True, random_state=35)

In [ ]:
X_train.shape

(800, 1)

In [ ]:
X_train=torch.from_numpy(X_train).float()
X_test = torch.from_numpy(X_test).float()
y_train = torch.from_numpy(y_train).float()
y_test = torch.from_numpy(y_test).float()


In [ ]:
type(X_train)

torch.Tensor

In [ ]:
X_train.shape

torch.Size([800, 1])

### Define the Model

In [ ]:
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = torch.nn.Linear(1, 12)
        self.fc2 = torch.nn.Linear(12, 12)
        self.fc3 = torch.nn.Linear(12, 12)
        self.fc4 = torch.nn.Linear(12, 1)

    def forward(self, x):
        x  = self.fc1(F.relu(x))
        x  = self.fc2(F.relu(x))
        x  = self.fc3(F.relu(x))
        x  = self.fc4(x)
        return x

    
    

In [ ]:
model =Net()

In [ ]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[ 0.7574],
        [-0.3018],
        [ 0.7458],
        [-0.4480],
        [ 0.9365],
        [-0.6944],
        [ 0.7714],
        [-0.0030],
        [-0.4035],
        [ 0.5201],
        [ 0.5837],
        [-0.9619]], requires_grad=True)
Parameter containing:
tensor([-0.6820,  0.0617,  0.6427, -0.9894, -0.9912, -0.7999,  0.9310,  0.0080,
         0.1815,  0.0402,  0.0900, -0.9745], requires_grad=True)
Parameter containing:
tensor([[ 0.0824, -0.0328,  0.2560,  0.2775, -0.1645, -0.0790,  0.0500, -0.0849,
          0.2584,  0.1496, -0.0171, -0.1180],
        [ 0.0455,  0.1867, -0.2062, -0.1045, -0.0239,  0.0675, -0.1812, -0.0086,
          0.0982, -0.0780,  0.1087,  0.2080],
        [-0.2859,  0.2428,  0.0692,  0.2100,  0.2518, -0.0720, -0.0171, -0.1023,
         -0.0103, -0.0959,  0.1177,  0.0436],
        [-0.2745, -0.1630, -0.2816, -0.2562, -0.0077,  0.0789, -0.0974, -0.0781,
          0.1017, -0.2514, -0.2773,  0.1313],
        [ 0.0143,  0.1640,  0.12

In [ ]:
for children in model.children():
    print(children)

Linear(in_features=1, out_features=12, bias=True)
Linear(in_features=12, out_features=12, bias=True)
Linear(in_features=12, out_features=12, bias=True)
Linear(in_features=12, out_features=1, bias=True)


In [ ]:
model = Net()

# The nn package also contains definitions of popular loss functions; in this
# case we will use Mean Squared Error (MSE) as our loss function.
loss_fn = torch.nn.MSELoss()
t=0

optimizer = optim.Adam(model.parameters(), lr=0.001)
for epch in range(100):
    for x,y in zip(X_train,y_train):
        y_pred = model(x)
        loss = loss_fn(y_pred, y)
        
        t=t+1
        if t % 100 == 99:
            print(t, loss.item())

        model.zero_grad()
        loss.backward()
        optimizer.step()

99 1263517.625
199 7237.50830078125
299 628.9041137695312
399 298463.15625
499 13277.927734375
599 17354.396484375
699 9773.580078125
799 32398.275390625
899 80156.65625
999 29749.44921875
1099 2166.6640625
1199 86223.671875
1299 19263.78515625
1399 14087.541015625
1499 2005.8427734375
1599 19366.4921875
1699 64420.69140625
1799 17672.013671875
1899 61.72430419921875
1999 65206.3828125
2099 18049.267578125
2199 11337.6806640625
2299 44.89512252807617
2399 10826.0615234375
2499 53108.53125
2599 9504.2939453125
2699 61.649497985839844
2799 48346.89453125
2899 16178.1123046875
2999 8445.99609375
3099 181.5603485107422
3199 4317.69970703125
3299 43052.8828125
3399 3420.608642578125
3499 3.498518943786621
3599 33922.15625
3699 13545.080078125
3799 5789.26953125
3899 3.389195203781128
3999 698.5175170898438
4099 33880.98046875
4199 437.9537658691406
4299 297.287109375
4399 22693.42578125
4499 10721.955078125
4599 3554.864013671875
4699 208.1248779296875
4799 7.341490268707275
4899 25520.1601

34999 5.621362209320068
35099 2.6428322792053223
35199 1.1952545642852783
35299 3.090333938598633
35399 0.31645774841308594
35499 41.00787353515625
35599 2.87532639503479
35699 4.385578155517578
35799 5.405823707580566
35899 2.8128697872161865
35999 1.1125266551971436
36099 3.3456125259399414
36199 0.3064352869987488
36299 40.4172248840332
36399 2.90895676612854
36499 3.4198131561279297
36599 5.88574743270874
36699 3.060767889022827
36799 1.0138722658157349
36899 3.1446475982666016
36999 0.27431437373161316
37099 41.75828170776367
37199 3.8108835220336914
37299 3.8149356842041016
37399 6.188506603240967
37499 3.1715266704559326
37599 0.7593626976013184
37699 3.0663464069366455
37799 0.22136037051677704
37899 41.5228271484375
37999 3.9053518772125244
38099 3.810168743133545
38199 6.291726112365723
38299 3.3111181259155273
38399 0.700412392616272
38499 2.5435421466827393
38599 0.19104592502117157
38699 41.326351165771484
38799 3.7246360778808594
38899 3.6852798461914062
38999 6.118104457

67899 11.787071228027344
67999 0.38513222336769104
68099 0.8500785827636719
68199 0.09772779047489166
68299 24.835172653198242
68399 1.265350341796875
68499 2.4562106132507324
68599 3.9347167015075684
68699 11.983660697937012
68799 0.40106022357940674
68899 0.8330572843551636
68999 0.10894149541854858
69099 24.765871047973633
69199 1.2008328437805176
69299 2.4799904823303223
69399 3.645782709121704
69499 12.213750839233398
69599 0.4112316966056824
69699 0.9795973300933838
69799 0.10726584494113922
69899 24.315793991088867
69999 1.2483806610107422
70099 2.4499013423919678
70199 3.4732956886291504
70299 12.579747200012207
70399 0.42967328429222107
70499 1.060457468032837
70599 0.10910776257514954
70699 23.89564323425293
70799 1.2626055479049683
70899 2.3959388732910156
70999 3.335684061050415
71099 12.859967231750488
71199 0.4451941251754761
71299 1.1348803043365479
71399 0.11058446019887924
71499 23.570409774780273
71599 1.27250075340271
71699 2.3439788818359375
71799 3.4747745990753174

In [ ]:
y_pred=model(X_test)

In [ ]:
y_pred

tensor([[55.4715],
        [43.2042],
        [44.4024],
        [61.5766],
        [55.1291],
        [52.3904],
        [60.7778],
        [12.1081],
        [15.8739],
        [14.2763],
        [17.6426],
        [14.0480],
        [21.3514],
        [48.5676],
        [27.9700],
        [12.3934],
        [41.3784],
        [12.5646],
        [30.8799],
        [38.9820],
        [14.9039],
        [59.7508],
        [14.5045],
        [35.8438],
        [40.6366],
        [54.5015],
        [14.7898],
        [60.9489],
        [32.7628],
        [28.8829],
        [19.5255],
        [22.6066],
        [63.6877],
        [53.5315],
        [51.3063],
        [19.6967],
        [38.9249],
        [52.6186],
        [55.3003],
        [36.3003],
        [52.7327],
        [64.8859],
        [58.6667],
        [26.0300],
        [23.5766],
        [24.2613],
        [40.4084],
        [52.0481],
        [20.2673],
        [43.2613],
        [31.7928],
        [23.2913],
        [28.